name: Update Latest GitHub Push in Profile README

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch:        # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest push event
        id: latest
        run: |
          curl -s https://api.github.com/users/${{ github.repository_owner }}/events/public > events.json
          latest_push=$(jq '[.[] | select(.type=="PushEvent")][0]' events.json)
          
          repo=$(echo "$latest_push" | jq -r '.repo.name')
          commit=$(echo "$latest_push" | jq -r '.payload.commits[-1].message')
          url="https://github.com/$repo/commit/$(echo "$latest_push" | jq -r '.payload.commits[-1].sha')"
          time=$(echo "$latest_push" | jq -r '.created_at')

          echo "REPO=$repo" >> $GITHUB_ENV
          echo "COMMIT=$commit" >> $GITHUB_ENV
          echo "URL=$url" >> $GITHUB_ENV
          echo "TIME=$time" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i '/<!-- LAST_PUSH_START -->/,/<!-- LAST_PUSH_END -->/c\
          <!-- LAST_PUSH_START -->\n\
          🔄 Last push to [${{ env.REPO }}](${{ env.URL }})\n\
          📄 Commit: _${{ env.COMMIT }}_\n\
          🕒 Time: `${{ env.TIME }}`\n\
          <!-- LAST_PUSH_END -->' README.md

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update latest push info" || exit 0
          git push
